variables:
  DOCKER_TLS_CERTDIR: "/certs"
  APP: "my-app"
  DOCKER_DRIVER: overlay2

default:
  before_script:
    - echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USERNAME" "$HARBOR_HOST" --password-stdin
  image:
    name: docker:24.0.5
    pull_policy: if-not-present

stages:
  - lint
  - build
  - test
  - qa

lint-job:
  stage: lint
  image: golang:1.24.3
  before_script:
    - go install honnef.co/go/tools/cmd/staticcheck@latest
    - export PATH=$PATH:$(go env GOPATH)/bin
  script:
    - staticcheck ./... | tee staticcheck-report.txt || true
    - mkdir -p reports
    - awk '{
        split($0, a, ":");
        file=a[1]; line=a[2]; msg=substr($0, index($0,$3));
        printf("<testcase classname=\"staticcheck\" name=\"%s\"><failure>%s:%s %s</failure></testcase>\n", file, file, line, msg);
      }' staticcheck-report.txt > reports/staticcheck.xml
    - echo "<testsuites><testsuite name=\"staticcheck\">" | cat - reports/staticcheck.xml <(echo "</testsuite></testsuites>") > junit-staticcheck.xml
  artifacts:
    paths:
      - staticcheck-report.txt
      - junit-staticcheck.xml
    reports:
      junit: junit-staticcheck.xml
    expire_in: 1 week

build:
  stage: build
  services:
    - docker:24.0.5-dind
  script:
    - docker build -f backend.Dockerfile -t my-backend-image .
    - docker tag my-backend-image $HARBOR_HOST/$HARBOR_PROJECT/backend:$CI_JOB_ID
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/backend:$CI_JOB_ID

    - docker build -f bot.Dockerfile -t my-bot-image .
    - docker tag my-bot-image $HARBOR_HOST/$HARBOR_PROJECT/bot:$CI_JOB_ID
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/bot:$CI_JOB_ID

container_scanning:
  stage: test
  image:
    name: $HARBOR_HOST/docker-hub-cache/aquasec/trivy:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    TRIVY_USERNAME: "$HARBOR_USERNAME"
    TRIVY_PASSWORD: "$HARBOR_PASSWORD"
    TRIVY_AUTH_URL: "$HARBOR_HOST"
    FULL_IMAGE_NAME: $HARBOR_HOST/$HARBOR_PROJECT/$APP:latest
  script:
    - trivy --version
    - trivy clean --scan-cache
    - time trivy image --download-db-only --no-progress --cache-dir .trivycache/
    - time trivy image --exit-code 0 --cache-dir .trivycache/ --no-progress --format template --template "@/contrib/gitlab.tpl" --output "$CI_PROJECT_DIR/gl-container-scanning-report.json" "$FULL_IMAGE_NAME"
    - time trivy image --exit-code 1 --cache-dir .trivycache/ --severity CRITICAL --no-progress "$FULL_IMAGE_NAME"
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    reports:
      container_scanning: gl-container-scanning-report.json
  tags:
    - docker
  needs:
    - build

unit-tests:
  stage: test
  image: golang:1.24.3
  before_script:
    - go install github.com/t-yuki/gocover-cobertura@latest
    - export PATH=$PATH:$(go env GOPATH)/bin
  script:
    - go mod tidy
    - go test -v -coverprofile=coverage.out ./...
    - gocover-cobertura < coverage.out > coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.out
      - coverage.xml
    expire_in: 1 week

integration-tests:
  stage: test
  image: golang:1.24.3
  script:
    - go mod tidy
    - go test -v ./DB

qa_scanning:
  stage: qa
  image:
    name: $HARBOR_HOST/docker-hub-cache/aquasec/trivy:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    TRIVY_USERNAME: "$HARBOR_USERNAME"
    TRIVY_PASSWORD: "$HARBOR_PASSWORD"
    TRIVY_AUTH_URL: "$HARBOR_HOST"
    FULL_IMAGE_NAME: $HARBOR_HOST/$HARBOR_PROJECT/$APP:latest
  script:
    - trivy --version
    - trivy clean --scan-cache
    - trivy image --download-db-only --no-progress --cache-dir .trivycache/
    - trivy image --exit-code 0 --cache-dir .trivycache/ --no-progress --format template --template "@/contrib/gitlab.tpl" --output "$CI_PROJECT_DIR/gl-container-scanning-report.json" "$FULL_IMAGE_NAME"
    - trivy image --exit-code 1 --cache-dir .trivycache/ --severity CRITICAL --no-progress "$FULL_IMAGE_NAME"
  cache:
    paths:
      - .trivycache/
  artifacts:
    when: always
    reports:
      container_scanning: gl-container-scanning-report.json
  needs:
    - build