variables:
  DOCKER_TLS_CERTDIR: "/certs"
  APP: "my-app"

stages:
  - build

build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
    - echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USERNAME" "$HARBOR_HOST" --password-stdin
  script:
    - docker build -t my-docker-image .
    - docker tag my-docker-image $HARBOR_HOST/$HARBOR_PROJECT/$APP:$CI_JOB_ID
    - docker tag my-docker-image $HARBOR_HOST/$HARBOR_PROJECT/$APP:latest
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/$APP:$CI_JOB_ID
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/$APP:latest
